reviewers:

  # Reviewer groups each of which has a list of GitHub usernames
  groups:
    defaultgroup:
      - BrianCArnold
    groupa:
      - SPR-Brian
    groupb:
      - SPR-Brian
      - BrianCArnold

files:
  # Keys are glob expressions.
  # You can assign groups defined above as well as GitHub usernames.
  '**':
    - defaultgroup
  'ProjectA/**':
    - groupa # group
  'ProjectA/FolderB':
    - groupb # group
  'ProjectB/**':
    - groupb # group

options:
  # If it's true, the last matching files-change pattern takes the most precedence (CODEOWNERS-compatible)
  # See https://github.com/necojackarc/auto-request-review/pull/80 for more details.
  last_files_match_only: false