groups:
  defaults:
    members:
      - BrianCArnold
      - SPR-Brian
    required: 1
    paths:
      - '**'
  Project-A:
    members:
      - SPR-Brian
    required: 1
    paths:
      - 'ProjectA/**'
  Project-B:
    members:
      - BrianCArnold
      - FakeUser
    required: 2
    paths:
      - 'ProjectB/**'
  Project-C:
    members:
      - FakeUser
    required: 1
    paths:
      - 'ProjectC/**'