groups:
  defaults:
    members:
      - team:DefaultGroup
    required: 1
    paths:
      - '**'
  Fix:
    members:
      - team:Fix
    required: 2
    paths:
      - 'assemblies/SRFixMaster/**'
      - 'assemblies/SRFixBase/**'
  Risk:
    members:
      - team:GroupB
    required: 2
    paths:
      - 'assemblies/Risk/**'