name: Require Review

permissions: write-all

on:
  pull_request_review:
    types: [editted, submitted]

jobs:
  require-review:
    name: Require Review
    runs-on: ubuntu-latest
    steps:
      - name: Request review based on files changes
        uses: briancarnold/requireuserapproval@debug24
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
