name: Require Review

permissions: write-all

on:
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  require-review:
    name: Require Review
    runs-on: ubuntu-latest
    steps:
      - name: Request review based on files changes
        uses: briancarnold/requireuserapproval@v0.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}