name: Require Review

permissions: write-all

on:
  pull_request_review:
    types: [editted, submitted]

jobs:
  require-review:
    name: Require Review
    runs-on: ubuntu-latest
    steps:
      - name: Require User Approval
        uses: BrianCArnold/RequireUserApproval@0.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}